# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

target 'bankcard' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  use_frameworks! 

  # Pods for bankcard
  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'RCTText',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTWebSocket', 
    'RCTImage',
    'RCTNetwork',
    'ART',
  ]

  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  target 'bankcardTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
